# Generated by Django 5.1.6 on 2025-02-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_remove_user_is_admin_remove_user_otp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("member", "member")],
                default="member",
                max_length=10,
            ),
        ),
    ]
