# Generated by Django 5.1.6 on 2025-02-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_userprofile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("member", "member")],
                default="member",
                max_length=10,
            ),
        ),
    ]
