# Generated by Django 5.1.5 on 2025-02-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='webmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
