# Generated by Django 5.1.5 on 2025-02-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='conclusion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='general_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='points',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hoerimagesmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='designation',
            field=models.TextField(),
        ),
    ]
