# Generated by Django 5.1.5 on 2025-02-16 04:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_services_name_webmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmodel',
            name='workflow',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='hoerimagesmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='designation',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='webmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
