# Generated by Django 5.1.5 on 2025-02-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_portfolio_backend_technologies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
    ]
