# Generated by Django 5.1.6 on 2025-02-09 10:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_portfolio_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(default="test"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="conclusion",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="general_info",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="section",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="team",
            name="designation",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
