# Generated by Django 5.1.6 on 2025-02-11 04:58

import ckeditor_uploader.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_about_description_alter_blogpost_conclusion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experiences",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("company_name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="images/experiences")),
                ("points", ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
                "ordering": ["-created_at"],
            },
        ),
    ]
