# Generated by Django 5.1.6 on 2025-02-11 05:45

import ckeditor_uploader.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_experiences"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoerImagesModel",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="images/hero")),
                ("head", models.CharField(max_length=255)),
                ("description", ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
