# Generated by Django 5.1.6 on 2025-02-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_hoerimagesmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoerimagesmodel",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/hero"),
        ),
    ]
