# Generated by Django 5.1.6 on 2025-02-11 09:36

import ckeditor_uploader.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_hoerimagesmodel_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Benefits",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", ckeditor_uploader.fields.RichTextUploadingField()),
                ("image", models.ImageField(upload_to="services/")),
                ("icon", models.ImageField(upload_to="services/icon/")),
                ("benefit", models.ManyToManyField(to="core.benefits")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.category"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
