# Generated by Django 5.1.6 on 2025-02-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_benefits_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/services"),
        ),
        migrations.AlterField(
            model_name="services",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
    ]
