# Generated by Django 5.1.5 on 2025-02-16 11:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='images/workflow/')),
            ],
        ),
    ]
